kind: Pod
apiVersion: v1
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  containers:
    - name: echo-server
      image: romanowalex/echo-server:v2.0
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: simple
---
kind: Service
apiVersion: v1
metadata:
  name: echo-server
spec:
  type: NodePort
  selector:
    app: echo-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
