global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'echoserver-metrics'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - default
    selectors:
    - role: "pod"
      label: "app.kubernetes.io/name=echoserver"
